config/routes.rb
RedmineApp::Application.routes.draw do
  get 'autolog_time_entries' => 'autolog_time_entries#index'
  match '/autolog_time_entries/save', :to => 'autolog_time_entries#save', :via => [:post], :as => 'perform_autolog_time_entries'
end

app/controllers/autolog_time_entries_controller.rb
class AutologTimeEntriesController < ApplicationController
	layout 'base'
	before_filter :get_users, :only => [:index]

	def index
	end

	def save
		if request.post?
			begin
		  		@unsaved_entries = {}
		  		@saved_entries = {}
			  	te = {}
			  		
			  	if (params[:time_entry_autolog][:start_date].to_date <= params[:time_entry_autolog][:end_date].to_date)
			  		user = User.find(params[:time_entry_autolog][:user_id])
			  		issue = Issue.find(params[:time_entry_autolog][:issue_id])
			  		if (user.present? and issue.present?)
				  		start_date = params[:time_entry_autolog][:start_date].to_date
				  		end_date = params[:time_entry_autolog][:end_date].to_date
				  		hours = params[:time_entry_autolog][:hours].to_f
				  		number_of_days = weekdays_in_date_range(start_date..end_date)

				  		if (params[:time_entry_autolog][:mode] == 'winter' and Setting.plugin_redmine_time_entry_autolog['winter_workday_hours'].present?)
				  			remaining_hours = hours

				  			(start_date..end_date).each do |d|
				  				if d.cwday < 6 and Setting.plugin_redmine_time_entry_autolog['winter_workday_hours'][d.cwday.to_s].present?
				  					remaining_hours -= (Setting.plugin_redmine_time_entry_autolog['winter_workday_hours'][d.cwday.to_s]).to_f
				  				end
				  			end

				  			workday_hours = remaining_hours/number_of_days

			  			elsif (params[:time_entry_autolog][:mode] == 'equitable')
			  				workday_hours = hours/number_of_days
			  			end

				  		(start_date..end_date).each do |d|
				  			if d.cwday < 6
				  				te[:user] = user
						  		te[:issue] = issue
						  		te[:spent_on] = d
						  		if (params[:time_entry_autolog][:mode] == 'winter' and Setting.plugin_redmine_time_entry_autolog['winter_workday_hours'][d.cwday.to_s].present?)
						  			te[:hours] = workday_hours + Setting.plugin_redmine_time_entry_autolog['winter_workday_hours'][d.cwday.to_s].to_f
						  		else
						  			te[:hours] = workday_hours
						  		end
					  			time_entry = TimeEntry.create(te)

					  			if time_entry.new_record?
					        		@unsaved_entries[d] = time_entry
						      	else
						        	@saved_entries[d] = time_entry
						       	end
				  			end
				    	end
				    end
			  	end

			  	if @unsaved_entries.present?
			  		flash[:error] = l(:notice_import_finished_with_errors, :count => @unsaved_entries.count, :total => (@unsaved_entries.count + @saved_entries.count))
			  	else
			  		flash[:notice] = l(:notice_import_finished, :count => @saved_entries.count)
			  	end
			rescue
                flash[:error] = l(:'time_entry_autolog.error_autolog_failed')
            end
		  	
			respond_to do |format|
				format.js {}
			end

			redirect_to action: "index"
		end
	end

	def get_users
		@users = User.all.order(:login)
        @name_field = 'login'
	end

	protected
  	def weekdays_in_date_range(range)
    	range.select { |d| (1..5).include?(d.wday) }.size
  	end

end

app/views/autolog_time_entries/index.html.erb
<%#= javascript_include_tag 'application', plugin: 'redmine_time_entry_autolog' %>
<h2><%= l(:'time_entry_autolog.label_autolog_time_entries') %></h2>

<%= form_for :time_entry_autolog, remote: true, :url => perform_autolog_time_entries_path do |f| %>
	<fieldset class="box tabular">
		<legend>Imputar automáticamente en ticket</legend>
		<div class="splitcontentleft">
			<p><%= f.number_field :issue_id %>
			<%= f.label :issue_id, 'Ticket' %></p>
		</div>
		<div class="splitcontentright">
			<p><%= f.select :user_id, options_from_collection_for_select(@users, 'id', @name_field), {} %>
			<%= f.label :user_id, 'Autor' %></p>
		</div>
		<p><%= f.number_field :hours %>
		<%= f.label :hours, 'Horas' %></p>
		<div class="splitcontentleft">
			<p><%= f.text_field :start_date, :size => 10%><%= calendar_for('time_entry_autolog_start_date') %>
				<%= f.label :start_date, 'Fecha de inicio' %></p>
		</div>
		<div class="splitcontentright">
			<p><%= f.text_field :end_date, :size => 10%><%= calendar_for('time_entry_autolog_end_date') %>
				<%= f.label :end_date, 'Fecha fin' %></p>
		</div>
		<p>
			<%= f.label :mode, l(:'time_entry_autolog.label_autolog_mode') %>
			<% %w(winter equitable).each do |autolog_mode| %>
			    <%= f.radio_button :mode, autolog_mode %>
			    <%= f.label :mode, l(:"time_entry_autolog.#{autolog_mode}_autolog_mode"), :value => autolog_mode, :class => 'inline' %>
		    <% end %>
		</p>
		<%= submit_tag(l(:button_save)) %>
	</fieldset>
<% end %>

app/views/settings/_time_entry_autolog.html.erb
<fieldset>
	<legend><%=l(:"time_entry_autolog.label_prerequisites")%></legend>
	<p>
		<label><%=l(:"time_entry_autolog.label_authorized_users")%></label>
		<%= select_tag 'settings[authorized_users]', options_from_collection_for_select(User.active, 'id', 'login', @settings['authorized_users']), multiple: true %>
	</p>
</fieldset>
<fieldset>
	<legend><%=l(:"time_entry_autolog.label_work_schedule")%></legend>

	<%
	workdays = [1,2,3,4,5]
	if !@settings['winter_workday_hours'].present?
		@settings['winter_workday_hours'] = {}
	end
	%>

	<table border="1">
		<thead>
	  		<tr>
	  			<th></th>
	  			<% workdays.each do |i|%>
	  				<th><%=l(:"date.abbr_day_names")[i]%></th>
	  			<% end %>
	  		</tr>
	  	</thead>
	  	<tbody>
	  		<tr>
	  			<th><%=l(:"time_entry_autolog.label_winter_work_day")%></th>
	  			<% workdays.each do |i|%>
	  				<td><%= number_field_tag 'settings[winter_workday_hours]['+i.to_s+']', @settings['winter_workday_hours'][i.to_s], {:min => 0} %></td>
	  			<% end %>
	  		</tr>
	  	</tbody>
  	</table>
</fieldset>